### ISSUE TITLE
Bumping up HTCondor version to 10.2.0

### ISSUE THREAD

**Issue by amizeranschi** [usegalaxy-eu/vgcn#49]
Would it be possible to bump up the version of HTCondor to 10.2.0? Some tools that I work with have it as a requirement, for example: https://github.com/DataBiosphere/toil/issues/4315#issuecomment-1397732586

**Comment by bgruening** [comment]
Yes, we are working on this. Any help appreciated.

**Comment by bgruening** [comment]
Plan is to upgrade to Rockey Linux 9 and htcondor 10.

**Comment by amizeranschi** [comment]
Thanks for considering this. My colleague @otimusone and I have had a look at this repo and tried to get it to work in the last weeks, but we haven't had any luck so far. We're not sure why, perhaps it's a problem with the qemu or packer versions that we used.

Could you let us know which OS and tool versions you are using for building the images?

**Comment by bgruening** [comment]
We use Linux, I get working on Fedora or Ubuntu based OS.

**Comment by amizeranschi** [comment]
I tried on Ubuntu 20.04, using packer 1.8.5 and qemu 7.2.0. With these, I ran into the problems mentioned here: https://github.com/usegalaxy-eu/vgcn-infrastructure/issues/178 and the resulting image was 2.5 GB in size, so less than half on the latest Rocky Linux from [here](https://usegalaxy.eu/static/vgcn/). This indicates that the build process didn't manage complete, for whatever reason.

Which versions of ansible, packer and qemu are you using? Are there any other important dependencies to have a look at, apart from these?

P.S. I was building the image on a VM hosted in OpenStack. Could this cause any issues with qemu? Does it need to run on bare-metal?

**Comment by mira-miracoli** [comment]
Hi, have you tried to start the second build step, and if yes, did what was the result?
Have you watched if the building process failed at some point, eg. with Remmina?
Which step is currently failing for you? 
I tried to build it locally with packer 1.8.5 and qemu-kvm 7.0.0 and ansible 6.7.0 and I made it now to the second build step, but ansible is failing to establish connection via the packer provisioner.

I think it doesn't need to run on bare-metal, but had a same thought. We use openstack, too and I was able to get in the first build step. The builds we made earlier (in 2020 actually) were running in the OpenStack cloud, too.

**Comment by amizeranschi** [comment]
Hi, and thanks for looking into this.

What is the second build step? I was only going by what I saw in the README, which was to run `make rockylinux-8.x-x86_64/base`. So my understanding is that this should run all of the build steps for creating the image, correct?

**Comment by amizeranschi** [comment]
Hmm, looks like I was using the wrong make target. What is the difference between those three "provisioning" target types, `vgcn-bwcloud`, `jenkins` and `generic`?

I see the README was now updated to recommend running `make rockylinux-8.x-x86_64/vgcn-bwcloud`. I will try this and see how that goes.

**Comment by mira-miracoli** [comment]
As far as I understand, you need to create the base taget first and then the specific image like "generic"

**Comment by mira-miracoli** [comment]
the Ansible connection problem was fixed for me with #55 
now I have a python version issue.. I guess there is still a lot to do

**Comment by amizeranschi** [comment]
I tried building now with `make rockylinux-8.x-x86_64/vgcn-bwcloud` and things progressed, the ansible stuff started running, but soon it crashed. Seems to be a problem with an scp command somewhere:

```
2023/01/26 16:25:57 packer-provisioner-ansible plugin: [INFO] 0 bytes written for 'stdout'
2023/01/26 16:25:57 packer-provisioner-ansible plugin: [INFO] 0 bytes written for 'stderr'
2023/01/26 16:25:57 packer-provisioner-ansible plugin: [INFO] RPC client: Communicator ended with: 0
2023/01/26 16:25:57 packer-provisioner-ansible plugin: [INFO] 0 bytes written for 'stdin'
    qemu: fatal: [default]: FAILED! => {"msg": "failed to transfer file to /home/amizeranschi/.ansible/tmp/ansible-local-696997d40l_4jd/tmpx2ag2s46 /root/.ansible/tmp/ansible-tmp-1674743156.1711838-697002-26454579274767/AnsiballZ_setup.py:\n\nunknown option -- O\r\nusage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]\n            [-J destination] [-l limit] [-o ssh_option] [-P port]\n            [-S program] source ... target\n"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    qemu:
2023/01/26 16:25:57 packer-provisioner-ansible plugin: shutting down the SSH proxy
2023/01/26 16:25:57 [INFO] (telemetry) ending ansible
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
2023/01/26 16:25:57 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5992: use of closed network connection
2023/01/26 16:25:57 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:2308: use of closed network connection
==> qemu: Deleting output directory...
2023/01/26 16:25:57 [INFO] (telemetry) ending qemu
==> Wait completed after 29 seconds 724 milliseconds
2023/01/26 16:25:57 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2023/01/26 16:25:57 machine readable: qemu,error []string{"Error executing Ansible: Non-zero exit status: exit status 2"}
==> Builds finished but no artifacts were created.
Build 'qemu' errored after 29 seconds 724 milliseconds: Error executing Ansible: Non-zero exit status: exit status 2
```

**Comment by mira-miracoli** [comment]
yes this looks like the issue Packer has since OpenSSH9, see #55 
OpenSSH 9 uses SFTP instead of SCP by default now (from [here](https://github.com/kinvolk/image-builder/commit/32dce37b69845cce50e06dc90765505427eb37d1))

**Comment by amizeranschi** [comment]
OK, installing OpenSSH 9 fixed that problem. Now, when trying to build Rocky 8 via `make rockylinux-8.x-x86_64/vgcn-bwcloud`, I get the following:

```
    qemu: failed: [default] (item=['singularity']) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package singularity available."], "item": ["singularity"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=25   changed=15   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0
    qemu:
```

And it looks like there isn't a `singularity` package for EL8, although there is one for EL7): https://pkgs.org/search/?q=singularity

The available package for EL8 and EL9 seems to be `singularity-ce`. I tried replacing `singularity` with `singularity-ce` here: https://github.com/usegalaxy-eu/ansible-collection-handy/blob/main/roles/os_setup/defaults/main.yml#L62

And this got things moving further, but `singularity-ce` ended up failing to install:

```
    qemu: fatal: [default]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: problem with installed package singularity-ce-3.10.5-1.el8.x86_64\n  - package singularity-ce-3.10.5-1.el8.x86_64 requires runc, but none of the providers can be installed\n  - package containerd.io-1.6.15-3.1.el8.x86_64 conflicts with runc provided by runc-1:1.1.4-1.module+el8.7.0+1122+04a7498b.x86_64\n  - package containerd.io-1.6.15-3.1.el8.x86_64 obsoletes runc provided by runc-1:1.1.4-1.module+el8.7.0+1122+04a7498b.x86_64\n  - package containerd.io-1.6.15-3.1.el8.x86_64 conflicts with runc provided by runc-1:1.1.4-1.module+el8.7.0+1078+e72fcd4f.x86_64\n  - package containerd.io-1.6.15-3.1.el8.x86_64 obsoletes runc provided by runc-1:1.1.4-1.module+el8.7.0+1078+e72fcd4f.x86_64\n  - cannot install the best candidate for the job\n  - package runc-1.0.0-56.rc5.dev.git2abd837.module+el8.5.0+681+c9a1951f.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-66.rc10.module+el8.5.0+770+e2f49861.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-73.rc95.module+el8.7.0+1076+9b1c11c1.x86_64 is filtered out by modular filtering\n  - package runc-1:1.1.4-1.module+el8.7.0+1077+0e4f03d4.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=55   changed=41   unreachable=0    failed=1    skipped=22   rescued=0    ignored=0
    qemu:
```

**Comment by amizeranschi** [comment]
Similarly, when building `rockylinux-9.x-x86_64/vgcn-bwcloud`, it complains about missing `python36` and `python38` and other packages:

```
    qemu: fatal: [default]: FAILED! => {"changed": false, "failures": ["No package python36 available.", "No package python38 available.", "No package python38-devel available."], "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides python3-wheel-wheel needed by python3-virtualenv-20.17.1-1.el9.noarch", "rc": 1, "results": []}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    qemu:
```

And indeed, these don't appear to be available for EL9: https://pkgs.org/search/?q=python38

@mira-miracoli Before moving on to upgrading to Rocky 9, do you have any idea about how things could be fixed with singularity for Rocky 8? It could be helpful to have that working once again, for now.

**Comment by mira-miracoli** [comment]
Hi @amizeranschi 
1. Singularity was renamed to "Apptainer" in 2021, so I changed the package to [`apptainer`](https://pkgs.org/search/?q=apptainer)
2. Rocky 9 does not have versioned python executable names, but the Python 3.9 that comes with it should be fine, so you can simple remove these dependencies for Rocky 9 by adding a conditional below: 
 ```yaml
when not ansible_distribution_major_version == '9'
```
3. Also the `python-virtualenv` package was dropped in EL 9 so we have to set a variable for the pulsar role:
```yaml
- role: galaxyproject.pulsar
  vars:
  - virtualenv_command: "python -m venv"
 ```
 4. I added new packages for Rocky 9 to make it work: `python3-devel` , `python3-pip` and `libcurl-devel`
 5. WIP: Rocky 9 uses GID 999 and UID 999, so we can't simply use it for galaxy. I am working on the [handy_os role](https://github.com/usegalaxy-eu/ansible-collection-handy/tree/main/roles/os_setup) to fix that

I will hopefully be able to push all my changes today or tomorrow and update the roles roles.

**Comment by amizeranschi** [comment]
For the record, in the case of Rocky 8, replacing `singularity` with `apptainer` [in here](https://github.com/usegalaxy-eu/ansible-collection-handy/blob/main/roles/os_setup/defaults/main.yml#L62) did solve the previous issue, but then the build process complained about failing to validate a GPG signature:

```
    qemu: fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for telegraf-1.17.2-1.x86_64: Public key for telegraf-1.17.2-1.x86_64.rpm is not installed"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=77   changed=56   unreachable=0    failed=1    skipped=29   rescued=0    ignored=0
    qemu:

```
